### ISSUE TITLE
Issue with filtering with tags

### ISSUE THREAD

**Issue by tedawf** [sikozonpc/GopherSocial#10]
When fetching the user's feed without the param tags, I am getting 0 posts due to this sql condition `(p.tags @> $5 OR $5 = '{}')`

My suspicion is that `pq.Array(nil)` returns `NULL` instead of `'{}'`.

I changed my condition to `(p.tags @> $5 OR $5 IS NULL)` and it seems to work fine for me now.

**Comment by anvidev** [comment]
I ran into this issue as well. I solved it by changing the Parse function in pagination struct for tags to be:

```go
tags := qv.Get("tags")
if tags != "" {
	fq.Tags = strings.Split(tags, ",")
} else {
	fq.Tags = []string{}
}
```

This ensures that tags is never nil if no tags are provided.

**Comment by sikozonpc** [comment]
Thank you guys!
I've fixed it with @anvidev solution for now.
Let me know if it still doesn't work.
